const axios = require('axios');
const { v4: uuidv4 } = require('uuid');
var express = require('express');
const { route } = require('express/lib/application');
var router = express.Router();

axios.defaults.rejectUnauthorized = false;
process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

const apiDomain = 'api.jobpixel.com';

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

let accessToken;
let refreshToken;
let clientId = '#REAPLCETHIS';
let clientSecret = '#REAPLCETHIS';
let state;

router.get('/auth', function (req, res) {
  state = uuidv4();

  // build query string for authorization page.
  const query = new URLSearchParams({
    client_id: clientId,
    redirect_uri: 'http://localhost:4500/callback',
    response_type: 'code',
    grant_type: 'authorization_code',
    scope: 'library.read',
    // state: state
  });

  console.log(query, `https://${apiDomain}/oauth/authorize?${query}`)

  res.redirect(302, `https://${apiDomain}/oauth/authorize?${query}`);
});

router.get('/callback', async function(req, res) {
  // auth get auth code generated by the auth server.
  console.log(req.query.code)

  // build form data to issue access token and refresh token.
  const formData = {
    grant_type: 'authorization_code',
    client_id: clientId,
    client_secret: clientSecret,
    redirect_uri: 'http://localhost:4500/callback',
    code: req.query.code,
    scope: 'library.read',
  };

  // log form data for debugging.
  console.log(formData)

  const authResponse = await axios.post(`https://${apiDomain}/oauth/token`, formData);

  accessToken = authResponse.data.access_token
  refreshToken = authResponse.data.refresh_token

  console.log({
    accessToken, refreshToken
  })

  res.send(authResponse.data)
});

router.get('/refresh-access-token', async function (req, res) {
  const formData = {
    grant_type: 'refresh_token',
    client_id: clientId,
    client_secret: clientSecret,
    refresh_token: refreshToken
  }

  const refreshResponse = await axios.post(`https://${apiDomain}/oauth/token`, formData);

  accessToken = refreshResponse.data.access_token
  refreshToken = refreshResponse.data.refresh_token

  console.log({
    accessToken, refreshToken
  })

  res.send(refreshResponse.data)
});

router.get('/videos', async function (req, res) {
  const endpoint = `https://${apiDomain}/api/partners/v1/library/media/videos`;

  const videoResponse = await axios.get(endpoint, {
    headers: {
      'Authorization': `Bearer ${accessToken}`,
    }
  });

  res.send(videoResponse.data);

});

module.exports = router;
