const axios = require('axios');
const { v4: uuidv4 } = require('uuid');
var express = require('express');
const { route } = require('express/lib/application');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

let accessToken;
let refreshToken;
let clientId = '#REAPLCETHIS';
let clientSecret = '#REAPLCETHIS';
let state;

router.get('/auth', function (req, res) {
  state = uuidv4();

  // build query string for authorization page.
  const query = new URLSearchParams({
    client_id: clientId,
    redirect_uri: 'http://localhost:3000/callback',
    response_type: 'code',
    grant_type: 'authorization_code',
    scope: '*',
    state: state
  });

  console.log(query, `https://api.jobpixel.com/oauth/authorize?${query}`)

  res.redirect(301, `https://api.jobpixel.com/oauth/authorize?${query}`);
});

router.get('/callback', async function(req, res) {
  // auth get auth code generated by the auth server.
  console.log(req.query.code)

  // build form data to issue access token and refresh token.
  const formData = {
    grant_type: 'authorization_code',
    client_id: clientId,
    client_secret: clientSecret,
    redirect_uri: 'http://localhost:3000/callback',
    code: req.query.code
  };

  // log form data for debuging.
  console.log(formData)

  const authResponse = await axios.post('https://api.jobpixel.com/oauth/token', formData);

  accessToken = authResponse.data.access_token
  refreshToken = authResponse.data.refresh_token

  console.log({
    accessToken, refreshToken
  })

  res.send(authResponse.data)
});

router.get('/refresh-access-token', async function (req, res) {
  const formData = {
    grant_type: 'refresh_token',
    client_id: clientId,
    client_secret: clientSecret,
    refresh_token: refreshToken
  }

  const refreshResponse = await axios.post('https://api.jobpixel.com/oauth/token', formData);

  accessToken = refreshResponse.data.access_token
  refreshToken = refreshResponse.data.refresh_token

  console.log({
    accessToken, refreshToken
  })

  res.send(refreshResponse.data)
});

router.get('/videos', async function (req, res) {
  const endpoint = 'https://api.jobpixel.com/api/partners/v1/library/media/videos';

  const videoResponse = await axios.get(endpoint, {
    headers: {
      'Authorization': `Bearer ${accessToken}`,
    }
  });

  res.send(videoResponse.data);

});

module.exports = router;
